version: '3.7'

services:
  server:
    container_name: gym-bot-server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./db:/usr/src/app/db
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    container_name: gym-bot-redis
    image: redis:latest
    restart: always
    networks:
      - webnet
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

networks:
  webnet:
